export const DomainAPIURL = '/api/onboarding/getDomain'
export const SubDomainAPIURL = '/api/onboarding/getSubDomain'
export const SubmitAppAPIURL = '/api/onboarding/submitApplication'
export const DremioLoginAPI = 'https://findata-dev.worldbank.org/apiv2/login'
export const DremioCatalogAPI = 'https://findata-dev.worldbank.org/api/v3/catalog'
export const getDremioAPIURL = '/api/dremio/getCatalog'
export const AppCodeAPIURL = '/api/onboarding/getAppCode'
export const AddDomainAPIURL = '/api/onboarding/createDomain'