export const TestUserAPI = 'https://jsonplaceholder.typicode.com/users'
export const DomainAPIURL = '/api/onboarding/getDomain'
export const SubDomainAPIURL = '/api/onboarding/getSubDomain'
export const SubmitAppAPIURL = '/api/onboarding/submitApplication'
export const DremioCatalogAPI = 'https://findata-dev.worldbank.org/api/v3/catalog'